[2024-04-21T00:02:50.234+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:02:50.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:02:50.241+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:02:50.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:02:50.259+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:02:50.256+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:02:50.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:02:50.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.052 seconds
[2024-04-21T00:03:20.987+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:03:20.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:03:20.992+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:03:20.992+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:03:21.016+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:03:21.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:03:21.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:03:21.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.066 seconds
[2024-04-21T00:03:51.470+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:03:51.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:03:51.473+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:03:51.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:03:51.486+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:03:51.483+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:03:51.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:03:51.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.039 seconds
[2024-04-21T00:04:22.140+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:04:22.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:04:22.143+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:04:22.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:04:22.156+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:04:22.153+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:04:22.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:04:22.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.050 seconds
[2024-04-21T00:04:52.686+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:04:52.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:04:52.690+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:04:52.690+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:04:52.706+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:04:52.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:04:52.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:04:52.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.043 seconds
[2024-04-21T00:05:23.340+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:05:23.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:05:23.345+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:05:23.344+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:05:23.356+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:05:23.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:05:23.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:05:23.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.042 seconds
[2024-04-21T00:05:54.210+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:05:54.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:05:54.214+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:05:54.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:05:54.229+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:05:54.224+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:05:54.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:05:54.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.054 seconds
[2024-04-21T00:06:24.934+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:06:24.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:06:24.937+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:06:24.937+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:06:24.957+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:06:24.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:06:24.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:06:24.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.048 seconds
[2024-04-21T00:06:55.413+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:06:55.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:06:55.416+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:06:55.416+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:06:55.429+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:06:55.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:06:55.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:06:55.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.042 seconds
[2024-04-21T00:07:25.914+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:07:25.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:07:25.917+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:07:25.917+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:07:25.930+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:07:25.927+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:07:25.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:07:25.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.041 seconds
[2024-04-21T00:07:56.640+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:07:56.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:07:56.652+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:07:56.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:07:56.669+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:07:56.664+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 4, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:07:56.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:07:56.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.093 seconds
[2024-04-21T00:08:06.790+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:08:06.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:08:06.797+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:08:06.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:08:06.829+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:08:06.826+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:08:06.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:08:06.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.078 seconds
[2024-04-21T00:08:37.623+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:08:37.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:08:37.629+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:08:37.628+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:08:37.647+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:08:37.644+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:08:37.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:08:37.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.059 seconds
[2024-04-21T00:09:08.040+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:09:08.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:09:08.045+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:09:08.045+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:09:08.061+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:09:08.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:09:08.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:09:08.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.056 seconds
[2024-04-21T00:09:34.606+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:09:34.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:09:34.614+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:09:34.614+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:09:34.661+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:09:34.658+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:09:34.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:09:34.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.080 seconds
[2024-04-21T00:10:09.358+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:10:09.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:10:09.376+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:10:09.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:10:09.401+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:10:09.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:10:09.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:10:09.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.105 seconds
[2024-04-21T00:10:39.914+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:10:39.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:10:39.921+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:10:39.921+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:10:39.943+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:10:39.939+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:10:39.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:10:39.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.078 seconds
[2024-04-21T00:11:10.517+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:11:10.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:11:10.526+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:11:10.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:11:10.560+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:11:10.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:11:10.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:11:10.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.129 seconds
[2024-04-21T00:11:41.230+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:11:41.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:11:41.243+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:11:41.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:11:41.283+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:11:41.276+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:11:41.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:11:41.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.296 seconds
[2024-04-21T00:12:11.999+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:12:12.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:12:12.012+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:12:12.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:12:12.040+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:12:12.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:12:12.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:12:12.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.100 seconds
[2024-04-21T00:12:46.050+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:12:46.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:12:46.069+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:12:46.066+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:12:47.669+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:12:47.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:12:47.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:12:47.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 1.981 seconds
[2024-04-21T00:13:20.173+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:13:20.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:13:20.181+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:13:20.180+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:13:20.198+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:13:20.195+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:13:20.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:13:20.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.078 seconds
[2024-04-21T00:13:51.017+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:13:51.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:13:51.030+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:13:51.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:13:51.068+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:13:51.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:13:51.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:13:51.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.120 seconds
[2024-04-21T00:14:21.607+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:14:21.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:14:21.615+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:14:21.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:14:21.635+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:14:21.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:14:21.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:14:21.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.102 seconds
[2024-04-21T00:14:52.265+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:14:52.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:14:52.276+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:14:52.275+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:14:52.297+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:14:52.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:14:52.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:14:52.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.100 seconds
[2024-04-21T00:15:24.362+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:15:24.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:15:24.451+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:15:24.417+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:15:24.919+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:15:24.893+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:15:24.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:15:25.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.926 seconds
[2024-04-21T00:15:55.799+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:15:55.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:15:55.806+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:15:55.806+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:15:55.822+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:15:55.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:15:55.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:15:55.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.082 seconds
[2024-04-21T00:16:12.309+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:16:12.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:16:12.321+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:16:12.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:16:12.358+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:16:12.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:16:12.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:16:12.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.094 seconds
[2024-04-21T00:16:40.846+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:16:40.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:16:40.852+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:16:40.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:16:40.888+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:16:40.885+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:16:40.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:16:40.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.088 seconds
[2024-04-21T00:17:11.509+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:11.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:17:11.518+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:11.518+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:11.549+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:11.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:17:11.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:11.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.095 seconds
[2024-04-21T00:17:13.628+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:13.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:17:13.636+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:13.635+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:13.685+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:13.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:17:13.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:13.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.118 seconds
[2024-04-21T00:17:27.976+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:27.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:17:27.986+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:27.986+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:28.038+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:28.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:17:28.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:28.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.105 seconds
[2024-04-21T00:17:32.277+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:32.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:17:32.287+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:32.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:32.330+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:17:32.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:17:32.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:17:32.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.106 seconds
[2024-04-21T00:18:02.953+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:18:02.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:18:02.959+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:18:02.958+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:18:02.983+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:18:02.979+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:18:02.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:18:03.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T00:18:33.564+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:18:33.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:18:33.580+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:18:33.579+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:18:33.706+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:18:33.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:18:33.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:18:33.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.279 seconds
[2024-04-21T00:19:04.400+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:19:04.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:19:04.404+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:19:04.404+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:19:04.418+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:19:04.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:19:04.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:19:04.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.070 seconds
[2024-04-21T00:19:34.985+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:19:34.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:19:34.995+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:19:34.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:19:35.029+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:19:35.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:19:35.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:19:35.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.107 seconds
[2024-04-21T00:20:05.169+0000] {processor.py:161} INFO - Started process (PID=461) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:20:05.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:20:05.175+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:20:05.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:20:05.192+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:20:05.189+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:20:05.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:20:05.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.059 seconds
[2024-04-21T00:20:35.748+0000] {processor.py:161} INFO - Started process (PID=476) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:20:35.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:20:35.752+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:20:35.752+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:20:35.767+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:20:35.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:20:35.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:20:35.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T00:21:06.307+0000] {processor.py:161} INFO - Started process (PID=491) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:21:06.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:21:06.315+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:21:06.314+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:21:06.341+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:21:06.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:21:06.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:21:06.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.074 seconds
[2024-04-21T00:21:36.973+0000] {processor.py:161} INFO - Started process (PID=506) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:21:36.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:21:36.978+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:21:36.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:21:36.997+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:21:36.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:21:37.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:21:37.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.057 seconds
[2024-04-21T00:22:07.544+0000] {processor.py:161} INFO - Started process (PID=521) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:22:07.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:22:07.554+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:22:07.554+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:22:07.570+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:22:07.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:22:07.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:22:07.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T00:22:38.204+0000] {processor.py:161} INFO - Started process (PID=536) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:22:38.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:22:38.210+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:22:38.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:22:38.230+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:22:38.226+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:22:38.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:22:38.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.072 seconds
[2024-04-21T00:23:05.798+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:23:05.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:23:05.805+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:23:05.805+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:23:05.843+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:23:05.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:23:05.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:23:05.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.129 seconds
[2024-04-21T00:23:36.531+0000] {processor.py:161} INFO - Started process (PID=561) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:23:36.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:23:36.539+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:23:36.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:23:36.570+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:23:36.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:23:36.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:23:36.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.097 seconds
[2024-04-21T00:24:42.365+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:24:42.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:24:42.389+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:24:42.387+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:24:42.451+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:24:42.436+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:24:42.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:24:42.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.229 seconds
[2024-04-21T00:25:35.195+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:25:35.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:25:35.205+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:25:35.204+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:25:35.222+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:25:35.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:25:35.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:25:35.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.083 seconds
[2024-04-21T00:26:05.777+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:26:05.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:26:05.785+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:26:05.784+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:26:05.807+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:26:05.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:26:05.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:26:05.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.078 seconds
[2024-04-21T00:26:36.260+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:26:36.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:26:36.270+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:26:36.269+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:26:36.289+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:26:36.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:26:36.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:26:36.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.073 seconds
[2024-04-21T00:27:06.824+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:27:06.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:27:06.830+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:27:06.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:27:06.850+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:27:06.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:27:06.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:27:06.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.084 seconds
[2024-04-21T00:27:37.413+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:27:37.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:27:37.421+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:27:37.420+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:27:37.447+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:27:37.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:27:37.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:27:37.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.089 seconds
[2024-04-21T00:28:08.190+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:28:08.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:28:08.196+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:28:08.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:28:08.214+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:28:08.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:28:08.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:28:08.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.078 seconds
[2024-04-21T00:28:38.980+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:28:38.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:28:38.992+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:28:38.991+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:28:39.014+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:28:39.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:28:39.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:28:39.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.167 seconds
[2024-04-21T00:55:26.037+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:55:26.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:55:26.055+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:55:26.050+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:55:26.101+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:55:26.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:55:26.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:55:26.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.149 seconds
[2024-04-21T00:55:56.805+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:55:56.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:55:56.875+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:55:56.874+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:55:56.907+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:55:56.903+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:55:56.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:55:56.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.189 seconds
[2024-04-21T00:56:27.584+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:27.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:56:27.591+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:56:27.590+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:27.607+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:56:27.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2024-04-21T00:56:27.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:27.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.092 seconds
[2024-04-21T00:56:45.039+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:45.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:56:45.047+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:56:45.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:45.083+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:56:45.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:56:45.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:45.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.093 seconds
[2024-04-21T00:56:53.200+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:53.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:56:53.206+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:56:53.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:53.244+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:56:53.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:56:53.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:56:53.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.097 seconds
[2024-04-21T00:57:23.836+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:57:23.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:57:23.850+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:57:23.849+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:57:23.882+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:57:23.880+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:57:23.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:57:23.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.136 seconds
[2024-04-21T00:57:54.852+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:57:54.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:57:54.860+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:57:54.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:57:54.886+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:57:54.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:57:54.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:57:54.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.116 seconds
[2024-04-21T00:58:25.401+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:58:25.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:58:25.407+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:58:25.407+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:58:25.426+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:58:25.424+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:58:25.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:58:25.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.063 seconds
[2024-04-21T00:58:56.580+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:58:56.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:58:56.595+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:58:56.594+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:58:56.659+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:58:56.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:58:56.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:58:56.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.257 seconds
[2024-04-21T00:59:27.320+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:59:27.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:59:27.330+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:59:27.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:59:27.349+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:59:27.346+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T00:59:27.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:59:27.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.085 seconds
[2024-04-21T00:59:32.550+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T00:59:32.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T00:59:32.555+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:59:32.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:59:32.592+0000] {logging_mixin.py:188} INFO - [2024-04-21T00:59:32.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/venv/lib/python3.9/site-packages'
[2024-04-21T00:59:32.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T00:59:32.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.074 seconds
[2024-04-21T01:00:03.125+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:03.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:00:03.132+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:00:03.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:03.150+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:00:03.146+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/venv/lib/python3.9/site-packages'
[2024-04-21T01:00:03.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:03.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.048 seconds
[2024-04-21T01:00:23.277+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:23.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:00:23.284+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:00:23.284+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:23.317+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:00:23.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/dags/venv/lib/python3.9/site-packages'
[2024-04-21T01:00:23.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:23.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.112 seconds
[2024-04-21T01:00:50.169+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:50.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:00:50.176+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:00:50.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:50.220+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:00:50.217+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:00:50.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:00:50.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.103 seconds
[2024-04-21T01:01:20.886+0000] {processor.py:161} INFO - Started process (PID=347) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:01:20.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:01:20.893+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:01:20.893+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:01:20.917+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:01:20.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:01:20.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:01:20.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.088 seconds
[2024-04-21T01:01:51.978+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:01:51.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:01:51.986+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:01:51.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:01:52.001+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:01:51.998+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:01:52.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:01:52.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.056 seconds
[2024-04-21T01:02:22.590+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:02:22.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:02:22.604+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:02:22.603+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:02:22.634+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:02:22.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:02:22.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:02:22.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.102 seconds
[2024-04-21T01:02:55.375+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:02:55.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:02:55.410+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:02:55.405+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:02:55.547+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:02:55.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:02:55.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:02:55.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.441 seconds
[2024-04-21T01:03:26.602+0000] {processor.py:161} INFO - Started process (PID=407) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:03:26.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:03:26.639+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:03:26.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:03:26.730+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:03:26.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:03:26.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:03:26.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.414 seconds
[2024-04-21T01:03:57.159+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:03:57.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:03:57.169+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:03:57.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:03:57.192+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:03:57.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:03:57.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:03:57.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.126 seconds
[2024-04-21T01:04:28.169+0000] {processor.py:161} INFO - Started process (PID=437) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:04:28.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:04:28.176+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:04:28.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:04:28.195+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:04:28.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:04:28.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:04:28.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.089 seconds
[2024-04-21T01:04:58.879+0000] {processor.py:161} INFO - Started process (PID=452) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:04:58.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:04:58.890+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:04:58.889+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:04:58.905+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:04:58.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:04:58.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:04:58.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.087 seconds
[2024-04-21T01:05:29.427+0000] {processor.py:161} INFO - Started process (PID=467) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:05:29.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:05:29.436+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:05:29.435+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:05:29.452+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:05:29.449+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:05:29.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:05:29.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.079 seconds
[2024-04-21T01:05:59.979+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:05:59.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:05:59.985+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:05:59.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:06:00.006+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:05:59.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:06:00.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:06:00.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.076 seconds
[2024-04-21T01:06:30.529+0000] {processor.py:161} INFO - Started process (PID=497) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:06:30.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:06:30.537+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:06:30.537+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:06:30.560+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:06:30.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:06:30.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:06:30.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.082 seconds
[2024-04-21T01:07:01.270+0000] {processor.py:161} INFO - Started process (PID=512) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:07:01.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:07:01.278+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:07:01.277+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:07:01.293+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:07:01.290+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:07:01.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:07:01.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.074 seconds
[2024-04-21T01:07:31.916+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:07:31.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:07:31.923+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:07:31.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:07:31.937+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:07:31.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:07:31.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:07:31.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.065 seconds
[2024-04-21T01:08:02.520+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:08:02.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:08:02.527+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:08:02.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:08:02.543+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:08:02.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:08:02.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:08:02.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.069 seconds
[2024-04-21T01:08:33.129+0000] {processor.py:161} INFO - Started process (PID=557) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:08:33.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:08:33.135+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:08:33.134+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:08:33.154+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:08:33.151+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:08:33.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:08:33.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.069 seconds
[2024-04-21T01:09:03.596+0000] {processor.py:161} INFO - Started process (PID=572) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:09:03.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:09:03.606+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:09:03.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:09:03.623+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:09:03.619+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:09:03.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:09:03.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.072 seconds
[2024-04-21T01:09:34.130+0000] {processor.py:161} INFO - Started process (PID=587) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:09:34.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:09:34.137+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:09:34.136+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:09:34.154+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:09:34.150+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:09:34.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:09:34.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.079 seconds
[2024-04-21T01:10:04.607+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:10:04.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:10:04.613+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:10:04.612+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:10:04.627+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:10:04.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:10:04.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:10:04.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.058 seconds
[2024-04-21T01:10:34.974+0000] {processor.py:161} INFO - Started process (PID=617) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:10:34.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:10:34.980+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:10:34.979+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:10:34.993+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:10:34.990+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:10:34.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:10:35.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.061 seconds
[2024-04-21T01:11:05.469+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:11:05.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:11:05.475+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:11:05.475+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:11:05.489+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:11:05.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:11:05.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:11:05.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.066 seconds
[2024-04-21T01:11:35.938+0000] {processor.py:161} INFO - Started process (PID=647) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:11:35.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:11:35.947+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:11:35.947+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:11:35.961+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:11:35.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:11:35.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:11:35.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.063 seconds
[2024-04-21T01:12:06.494+0000] {processor.py:161} INFO - Started process (PID=662) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:12:06.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:12:06.499+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:12:06.499+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:12:06.516+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:12:06.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:12:06.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:12:06.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.076 seconds
[2024-04-21T01:12:36.952+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:12:36.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:12:36.958+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:12:36.957+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:12:36.975+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:12:36.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:12:36.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:12:37.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.068 seconds
[2024-04-21T01:13:07.401+0000] {processor.py:161} INFO - Started process (PID=692) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:13:07.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:13:07.408+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:13:07.407+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:13:07.426+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:13:07.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:13:07.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:13:07.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.081 seconds
[2024-04-21T01:13:37.872+0000] {processor.py:161} INFO - Started process (PID=707) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:13:37.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:13:37.877+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:13:37.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:13:37.890+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:13:37.887+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:13:37.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:13:37.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.052 seconds
[2024-04-21T01:14:08.392+0000] {processor.py:161} INFO - Started process (PID=722) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:14:08.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:14:08.398+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:14:08.397+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:14:08.411+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:14:08.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:14:08.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:14:08.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.049 seconds
[2024-04-21T01:14:38.795+0000] {processor.py:161} INFO - Started process (PID=737) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:14:38.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:14:38.800+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:14:38.799+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:14:38.811+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:14:38.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:14:38.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:14:38.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.038 seconds
[2024-04-21T01:15:09.191+0000] {processor.py:161} INFO - Started process (PID=752) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:15:09.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:15:09.196+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:15:09.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:15:09.208+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:15:09.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:15:09.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:15:09.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.041 seconds
[2024-04-21T01:15:39.951+0000] {processor.py:161} INFO - Started process (PID=767) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:15:39.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:15:39.960+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:15:39.959+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:15:39.976+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:15:39.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:15:39.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:15:40.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.059 seconds
[2024-04-21T01:16:10.667+0000] {processor.py:161} INFO - Started process (PID=782) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:16:10.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:16:10.741+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:16:10.736+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:16:10.961+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:16:10.942+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:16:10.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:16:11.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.419 seconds
[2024-04-21T01:16:41.950+0000] {processor.py:161} INFO - Started process (PID=797) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:16:41.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:16:41.955+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:16:41.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:16:41.967+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:16:41.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:16:41.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:16:42.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.166 seconds
[2024-04-21T01:17:12.550+0000] {processor.py:161} INFO - Started process (PID=812) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:17:12.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:17:12.568+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:17:12.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:17:12.634+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:17:12.620+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:17:12.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:17:12.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.275 seconds
[2024-04-21T01:17:43.074+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:17:43.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:17:43.083+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:17:43.082+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:17:43.105+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:17:43.101+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:17:43.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:17:43.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.088 seconds
[2024-04-21T01:18:13.897+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:18:13.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:18:13.919+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:18:13.918+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:18:13.953+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:18:13.941+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:18:13.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:18:14.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.147 seconds
[2024-04-21T01:18:44.494+0000] {processor.py:161} INFO - Started process (PID=857) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:18:44.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:18:44.506+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:18:44.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:18:44.532+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:18:44.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:18:44.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:18:44.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.118 seconds
[2024-04-21T01:19:15.068+0000] {processor.py:161} INFO - Started process (PID=872) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:19:15.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:19:15.080+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:19:15.079+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:19:15.108+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:19:15.095+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:19:15.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:19:15.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.171 seconds
[2024-04-21T01:19:45.726+0000] {processor.py:161} INFO - Started process (PID=887) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:19:45.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:19:45.734+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:19:45.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:19:45.752+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:19:45.748+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:19:45.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:19:45.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T01:20:19.694+0000] {processor.py:161} INFO - Started process (PID=902) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:20:19.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:20:19.699+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:20:19.699+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:20:19.717+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:20:19.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:20:19.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:20:19.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T01:20:50.630+0000] {processor.py:161} INFO - Started process (PID=917) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:20:50.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:20:50.662+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:20:50.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:20:50.740+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:20:50.732+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:20:50.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:20:50.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.179 seconds
[2024-04-21T01:21:21.043+0000] {processor.py:161} INFO - Started process (PID=932) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:21:21.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:21:21.062+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:21:21.061+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:21:21.077+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:21:21.073+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:21:21.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:21:21.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.068 seconds
[2024-04-21T01:21:51.676+0000] {processor.py:161} INFO - Started process (PID=947) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:21:51.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:21:51.681+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:21:51.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:21:51.693+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:21:51.690+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:21:51.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:21:51.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.042 seconds
[2024-04-21T01:22:22.156+0000] {processor.py:161} INFO - Started process (PID=962) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:22:22.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:22:22.163+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:22:22.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:22:22.185+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:22:22.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:22:22.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:22:22.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.080 seconds
[2024-04-21T01:22:53.205+0000] {processor.py:161} INFO - Started process (PID=977) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:22:53.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:22:53.220+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:22:53.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:22:53.260+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:22:53.237+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:22:53.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:22:53.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.135 seconds
[2024-04-21T01:23:23.616+0000] {processor.py:161} INFO - Started process (PID=982) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:23:23.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:23:23.623+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:23:23.622+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:23:23.651+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:23:23.645+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:23:23.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:23:23.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.106 seconds
[2024-04-21T01:23:54.184+0000] {processor.py:161} INFO - Started process (PID=987) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:23:54.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:23:54.195+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:23:54.194+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:23:54.219+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:23:54.215+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:23:54.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:23:54.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.090 seconds
[2024-04-21T01:24:24.655+0000] {processor.py:161} INFO - Started process (PID=992) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:24:24.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:24:24.662+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:24:24.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:24:24.678+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:24:24.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:24:24.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:24:24.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.076 seconds
[2024-04-21T01:24:55.127+0000] {processor.py:161} INFO - Started process (PID=997) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:24:55.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:24:55.140+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:24:55.139+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:24:55.180+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:24:55.171+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:24:55.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:24:55.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.123 seconds
[2024-04-21T01:25:25.941+0000] {processor.py:161} INFO - Started process (PID=1002) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:25:25.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:25:25.976+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:25:25.974+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:25:26.036+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:25:26.020+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:25:26.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:25:26.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.224 seconds
[2024-04-21T01:25:56.394+0000] {processor.py:161} INFO - Started process (PID=1007) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:25:56.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:25:56.401+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:25:56.400+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:25:56.421+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:25:56.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:25:56.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:25:56.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.094 seconds
[2024-04-21T01:26:26.799+0000] {processor.py:161} INFO - Started process (PID=1012) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:26:26.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:26:26.805+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:26:26.805+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:26:26.823+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:26:26.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:26:26.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:26:26.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.106 seconds
[2024-04-21T01:26:57.231+0000] {processor.py:161} INFO - Started process (PID=1017) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:26:57.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:26:57.238+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:26:57.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:26:57.254+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:26:57.251+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:26:57.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:26:57.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.109 seconds
[2024-04-21T01:27:27.615+0000] {processor.py:161} INFO - Started process (PID=1022) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:27:27.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:27:27.622+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:27:27.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:27:27.640+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:27:27.636+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages'
[2024-04-21T01:27:27.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:27:27.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.093 seconds
[2024-04-21T01:27:43.905+0000] {processor.py:161} INFO - Started process (PID=1027) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:27:43.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:27:43.912+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:27:43.912+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:27:43.952+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:27:43.948+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: 'myenv/lib/python3.9/site-packages'
[2024-04-21T01:27:43.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:27:44.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.106 seconds
[2024-04-21T01:28:05.265+0000] {processor.py:161} INFO - Started process (PID=1032) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:28:05.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:28:05.272+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:28:05.271+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:28:05.307+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:28:05.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:28:05.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:28:05.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.099 seconds
[2024-04-21T01:28:35.667+0000] {processor.py:161} INFO - Started process (PID=1037) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:28:35.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:28:35.673+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:28:35.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:28:35.690+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:28:35.687+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:28:35.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:28:35.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.066 seconds
[2024-04-21T01:29:06.143+0000] {processor.py:161} INFO - Started process (PID=1042) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:29:06.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:29:06.149+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:29:06.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:29:06.168+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:29:06.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:29:06.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:29:06.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.132 seconds
[2024-04-21T01:29:36.574+0000] {processor.py:161} INFO - Started process (PID=1047) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:29:36.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:29:36.580+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:29:36.579+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:29:36.597+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:29:36.593+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:29:36.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:29:36.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.068 seconds
[2024-04-21T01:30:07.497+0000] {processor.py:161} INFO - Started process (PID=1052) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:30:07.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:30:07.531+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:30:07.529+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:30:07.588+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:30:07.578+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:30:07.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:30:07.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.223 seconds
[2024-04-21T01:30:38.199+0000] {processor.py:161} INFO - Started process (PID=1057) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:30:38.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:30:38.205+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:30:38.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:30:38.227+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:30:38.222+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:30:38.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:30:38.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.126 seconds
[2024-04-21T01:31:08.569+0000] {processor.py:161} INFO - Started process (PID=1062) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:31:08.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:31:08.577+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:31:08.576+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:31:08.594+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:31:08.590+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:31:08.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:31:08.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.083 seconds
[2024-04-21T01:31:39.110+0000] {processor.py:161} INFO - Started process (PID=1067) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:31:39.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:31:39.116+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:31:39.115+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:31:39.132+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:31:39.129+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:31:39.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:31:39.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.071 seconds
[2024-04-21T01:32:09.521+0000] {processor.py:161} INFO - Started process (PID=1072) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:32:09.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:32:09.534+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:32:09.533+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:32:09.552+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:32:09.548+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:32:09.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:32:09.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T01:32:39.914+0000] {processor.py:161} INFO - Started process (PID=1077) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:32:39.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:32:39.921+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:32:39.920+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:32:39.941+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:32:39.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:32:39.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:32:39.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.098 seconds
[2024-04-21T01:33:10.386+0000] {processor.py:161} INFO - Started process (PID=1082) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:33:10.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:33:10.411+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:33:10.409+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:33:10.443+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:33:10.438+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:33:10.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:33:10.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.143 seconds
[2024-04-21T01:33:40.788+0000] {processor.py:161} INFO - Started process (PID=1087) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:33:40.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:33:40.794+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:33:40.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:33:40.811+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:33:40.807+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:33:40.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:33:40.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.076 seconds
[2024-04-21T01:34:11.249+0000] {processor.py:161} INFO - Started process (PID=1092) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:11.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:34:11.257+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:34:11.256+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:11.279+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:34:11.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:34:11.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:11.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.092 seconds
[2024-04-21T01:34:41.665+0000] {processor.py:161} INFO - Started process (PID=1097) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:41.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:34:41.670+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:34:41.670+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:41.688+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:34:41.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project/myenv/lib/python3.9/site-packages'
[2024-04-21T01:34:41.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:41.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.067 seconds
[2024-04-21T01:34:51.859+0000] {processor.py:161} INFO - Started process (PID=1102) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:51.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:34:51.867+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:34:51.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:51.910+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:34:51.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:34:51.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:34:51.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.105 seconds
[2024-04-21T01:35:22.358+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:35:22.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:35:22.365+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:35:22.364+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:35:22.383+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:35:22.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:35:22.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:35:22.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.079 seconds
[2024-04-21T01:35:52.810+0000] {processor.py:161} INFO - Started process (PID=1112) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:35:52.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:35:52.816+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:35:52.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:35:52.832+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:35:52.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:35:52.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:35:52.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.069 seconds
[2024-04-21T01:36:23.290+0000] {processor.py:161} INFO - Started process (PID=1117) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:36:23.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:36:23.296+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:36:23.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:36:23.310+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:36:23.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:36:23.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:36:23.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.060 seconds
[2024-04-21T01:36:53.751+0000] {processor.py:161} INFO - Started process (PID=1122) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:36:53.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:36:53.761+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:36:53.760+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:36:53.799+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:36:53.791+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:36:53.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:36:53.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.108 seconds
[2024-04-21T01:37:29.882+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:37:29.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:37:29.894+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:37:29.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:37:29.918+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:37:29.914+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:37:29.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:37:29.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.075 seconds
[2024-04-21T01:38:00.309+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:00.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:38:00.320+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:38:00.318+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:00.338+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:38:00.334+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 9, in <module>
    os.chdir(script_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nadanisrinaseptiana/belajar/final_project'
[2024-04-21T01:38:00.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:00.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.093 seconds
[2024-04-21T01:38:05.448+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:05.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:38:05.455+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:38:05.454+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:05.489+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:38:05.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:38:05.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:05.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.102 seconds
[2024-04-21T01:38:35.842+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:35.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:38:35.855+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:38:35.854+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:35.896+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:38:35.889+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:38:35.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:38:35.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.160 seconds
[2024-04-21T01:39:06.211+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:39:06.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:39:06.220+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:39:06.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:39:06.244+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:39:06.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:39:06.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:39:06.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.094 seconds
[2024-04-21T01:39:36.772+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:39:36.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:39:36.779+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:39:36.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:39:36.797+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:39:36.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:39:36.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:39:36.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.062 seconds
[2024-04-21T01:40:07.231+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:40:07.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:40:07.237+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:40:07.236+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:40:07.259+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:40:07.251+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:40:07.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:40:07.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.089 seconds
[2024-04-21T01:41:00.118+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:41:00.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:41:00.125+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:41:00.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:41:00.141+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:41:00.138+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:41:00.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:41:00.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.052 seconds
[2024-04-21T01:41:30.497+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:41:30.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:41:30.502+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:41:30.502+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:41:30.517+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:41:30.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:41:30.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:41:30.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.068 seconds
[2024-04-21T01:42:00.854+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/nft_etl.py
[2024-04-21T01:42:00.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nft_etl.py for tasks to queue
[2024-04-21T01:42:00.858+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:42:00.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:42:00.872+0000] {logging_mixin.py:188} INFO - [2024-04-21T01:42:00.870+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/nft_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/nft_etl.py", line 8, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
[2024-04-21T01:42:00.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nft_etl.py
[2024-04-21T01:42:00.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nft_etl.py took 0.050 seconds
